package com.guying.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.guying.common.result.ScrollResult;
import com.guying.pojo.dto.AttractionCreateDTO;
import com.guying.pojo.dto.AttractionListQueryDTO;
import com.guying.pojo.dto.AttractionUpdateDTO;
import com.guying.pojo.entity.Attraction;
import com.guying.pojo.entity.AttractionFaq;
import com.guying.pojo.vo.AttractionAdditionVO;
import com.guying.pojo.vo.AttractionDetailVO;
import com.guying.pojo.vo.AttractionListVO;
import com.guying.pojo.vo.DocumentsQueryVO;
import jakarta.validation.Valid;

import java.util.List;

public interface AdminAttractionsService extends IService<Attraction> {
    AttractionAdditionVO addAttraction(AttractionCreateDTO attractionCreateDTO);

    AttractionDetailVO getAttractionDetail(Long attractionId);

    List<DocumentsQueryVO> getDocuments(Long attractionId);

    void deleteDocument(Long attractionId);

    String checkDocumentStatus(String taskId);

    void saveAutoGeneratedFaq(AttractionFaq attractionFaq);

    AttractionDetailVO updateAttraction( AttractionUpdateDTO attractionUpdateDTO);

    void deleteAttraction(Long attractionId);

    ScrollResult<AttractionListVO> getAttractionList(AttractionListQueryDTO attractionListQueryDTO);


}
