package com.guying.mq.consumer;

import com.guying.common.constants.MqConstants;
import com.guying.converter.AdminAttractionsConverter;
import com.guying.mapper.AttractionFaqMapper;
import com.guying.message.AttractionFqaMessage;
import com.guying.pojo.entity.Attraction;
import com.guying.pojo.entity.AttractionFaq;
import com.guying.service.AdminAttractionsService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;

import java.util.List;

@Component
@Slf4j
public class AdminAttractionListener {
    @Autowired
    private AdminAttractionsConverter adminAttractionsConverter;
    @Autowired
    private AdminAttractionsService adminAttractionsService;


    @RabbitListener(queues = MqConstants.ADMIN_SAVE_FAQ_QUEUE)
    public void saveFaqDocument(AttractionFqaMessage message) {
        log.info("收到保存faq消息: {}", message);
        AttractionFaq attractionFaq = adminAttractionsConverter.toAttractionFaq(message);
        adminAttractionsService.saveAutoGeneratedFaq(attractionFaq);
    }
}
